# Generated by Django 3.1 on 2020-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate_number', models.CharField(max_length=50)),
                ('type', models.CharField(default='Other', max_length=50)),
                ('is_valid', models.BooleanField(default=True)),
            ],
        ),
    ]
