# Generated by Django 3.1 on 2020-08-27 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='time_stamp',
            field=models.TimeField(default=datetime.datetime(2020, 8, 27, 18, 16, 1, 256474)),
        ),
    ]
