# Generated by Django 3.1 on 2020-08-27 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_vehicle_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='time_stamp',
            field=models.TimeField(default=datetime.datetime(2020, 8, 27, 18, 44, 38, 993678)),
        ),
    ]
